import Head from 'next/head';

export default function Home() {
  const test = "haha";
  console.log({ test })
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      Hello world
    </div>
  )
}
