import Head from 'next/head';

export default function Home() {
  return (
    <div data-testid="page-index">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>
        H1 Hello world
      </h1>
      <h2>
        H2 LALALA
      </h2>
      <p className="text-button">
        HMMMM
      </p>
    </div>
  )
}
