name: Cherry Pick Release to Main
on:
  pull_request:
    branches:
      - 'release'
    types: [closed]

jobs:
  cherry_pick_release_to_main:
    runs-on: ubuntu-latest
    name: Cherry pick into main
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && contains(github.head_ref, 'hotfix/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into release-v1.0
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: main
          labels: |
            hotfix
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
